FROM --platform=linux/amd64 python:3.11

WORKDIR /app

COPY . .
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV DB_HOST="db_invoice"

EXPOSE 8002

CMD sleep 15 && python3 -m uvicorn src.http_server:app --reload --host 0.0.0.0 --port 8002